const robi = [
  {
    id: "1",
    title: "দৈনিক-২ টাকা(+এসসি,ভ্যাট,এসডি)",
    renewable: "প্রতিদিন নবায়নযোগ্য",
    type: "daily",
    validity: 1,
    description: [""],
    charge: 2,
    link: "",
    service: {
      name: "ShowBiz Portal Auto",
      category: "428",
      keyWord: "SP",
      serviceid: "0307200003",
      productid: "0300404724",
    },
  },
  {
    id: "2",
    title: "দৈনিক-২ টাকা(+এসসি,ভ্যাট,এসডি)",
    renewable: "অ-নবায়নযোগ্য",
    type: "daily",
    validity: 1,
    description: [""],
    charge: 2,
    link: "",
    service: {
      name: "ShowBiz Portal Non Auto",
      category: "4281",
      keyWord: "SP1",
      serviceid: "0307200009",
      productid: "0300407732",
    },
  },
  {
    id: "3",
    title: "সাপ্তাহিক-৭ টাকা(+এসসি,ভ্যাট,এসডি)",
    renewable: "অ-নবায়নযোগ্য",
    type: "weekly",
    validity: 7,
    description: [""],
    charge: 7,
    link: "",
    service: {
     name: "ShowBiz Portal Non Auto",
      category: "4287",
      keyWord: "SP7",
      serviceid: "0307200009",
      productid: "0300407734",
    },
  },
  {
    id: "4",
    title: "পাক্ষিক-১৪ টাকা(+এসসি,ভ্যাট,এসডি)",
    renewable: "অ-নবায়নযোগ্য",
    type: "bi-weekly",
    validity: 15,
    description: [""],
    charge: 14,
    link: "",
   service: {
     name: "ShowBiz Portal Non Auto",
      category: "4285",
      keyWord: "SP15",
      serviceid: "0307200009",
      productid: "0300407736",
    },
  },
  {
    id: "5",
    title: "মাসিক-২৮ টাকা(+এসসি,ভ্যাট,এসডি)",
    renewable: "অ-নবায়নযোগ্য",
    type: "monthly",
    validity: 30,
    description: [""],
    charge: 28,
    link: "",
    service: {
     name: "ShowBiz Portal Non Auto",
      category: "4283",
      keyWord: "SP30",
      serviceid: "0307200009",
      productid: "0300407738",
    },
  },
];

const gp = [
  {
    id: "1",
    title: "দৈনিক-২ টাকা(+এসসি,ভ্যাট,এসডি)",
    renewable: "প্রতিদিন নবায়নযোগ্য",
    type: "daily",
    validity: 1,
    description: [""],
    charge: 2,
    link: "",
    service: {
      name: "ShowBiz Portal Auto",
      category: "428",
      keyWord: "SP",
      serviceid: "0307200003",
      productid: "0300404724",
    },
  },
  {
    id: "2",
    title: "দৈনিক-২ টাকা(+এসসি,ভ্যাট,এসডি)",
    renewable: "অ-নবায়নযোগ্য",
    type: "daily",
    validity: 1,
    description: [""],
    charge: 2,
    link: "",
    service: {
      name: "ShowBiz Portal Non Auto",
      category: "4281",
      keyWord: "SP1",
      serviceid: "0307200009",
      productid: "0300407732",
    },
  },
  {
    id: "3",
    title: "সাপ্তাহিক-৭ টাকা(+এসসি,ভ্যাট,এসডি)",
    renewable: "অ-নবায়নযোগ্য",
    type: "weekly",
    validity: 7,
    description: [""],
    charge: 7,
    link: "",
    service: {
     name: "ShowBiz Portal Non Auto",
      category: "4287",
      keyWord: "SP7",
      serviceid: "0307200009",
      productid: "0300407734",
    },
  },
  {
    id: "4",
    title: "পাক্ষিক-১৪ টাকা(+এসসি,ভ্যাট,এসডি)",
    renewable: "অ-নবায়নযোগ্য",
    type: "bi-weekly",
    validity: 15,
    description: [""],
    charge: 14,
    link: "",
   service: {
     name: "ShowBiz Portal Non Auto",
      category: "4285",
      keyWord: "SP15",
      serviceid: "0307200009",
      productid: "0300407736",
    },
  },
  {
    id: "5",
    title: "মাসিক-২৮ টাকা(+এসসি,ভ্যাট,এসডি)",
    renewable: "অ-নবায়নযোগ্য",
    type: "monthly",
    validity: 30,
    description: [""],
    charge: 28,
    link: "",
    service: {
     name: "ShowBiz Portal Non Auto",
      category: "4283",
      keyWord: "SP30",
      serviceid: "0307200009",
      productid: "0300407738",
    },
  },
];

const bl = [
  {
    id: "1",
    title: "দৈনিক-২ টাকা(+এসসি,ভ্যাট,এসডি)",
    renewable: "প্রতিদিন নবায়নযোগ্য",
    type: "daily",
    validity: 1,
    description: [""],
    charge: 2,
    link: "",
    service: {
      name: "ShowBiz Portal Auto",
      category: "428",
      keyWord: "SP",
      serviceid: "0307200003",
      productid: "0300404724",
    },
  },
  {
    id: "2",
    title: "দৈনিক-২ টাকা(+এসসি,ভ্যাট,এসডি)",
    renewable: "অ-নবায়নযোগ্য",
    type: "daily",
    validity: 1,
    description: [""],
    charge: 2,
    link: "",
    service: {
      name: "ShowBiz Portal Non Auto",
      category: "4281",
      keyWord: "SP1",
      serviceid: "0307200009",
      productid: "0300407732",
    },
  },
  {
    id: "3",
    title: "সাপ্তাহিক-৭ টাকা(+এসসি,ভ্যাট,এসডি)",
    renewable: "অ-নবায়নযোগ্য",
    type: "weekly",
    validity: 7,
    description: [""],
    charge: 7,
    link: "",
    service: {
     name: "ShowBiz Portal Non Auto",
      category: "4287",
      keyWord: "SP7",
      serviceid: "0307200009",
      productid: "0300407734",
    },
  },
  {
    id: "4",
    title: "পাক্ষিক-১৪ টাকা(+এসসি,ভ্যাট,এসডি)",
    renewable: "অ-নবায়নযোগ্য",
    type: "bi-weekly",
    validity: 15,
    description: [""],
    charge: 14,
    link: "",
   service: {
     name: "ShowBiz Portal Non Auto",
      category: "4285",
      keyWord: "SP15",
      serviceid: "0307200009",
      productid: "0300407736",
    },
  },
  {
    id: "5",
    title: "মাসিক-২৮ টাকা(+এসসি,ভ্যাট,এসডি)",
    renewable: "অ-নবায়নযোগ্য",
    type: "monthly",
    validity: 30,
    description: [""],
    charge: 28,
    link: "",
    service: {
     name: "ShowBiz Portal Non Auto",
      category: "4283",
      keyWord: "SP30",
      serviceid: "0307200009",
      productid: "0300407738",
    },
  },
];

export const PACKAGES = {
    robi,
    gp,
    bl
}
